
## Роль этапа сбора данных

Ноутбук выполняет получение и сохранение исходных данных.

Правила:
- исходные данные сохраняются в `raw/` без очистки и изменения схемы;
- сведения о файлах и источниках фиксируются в `docs/downloaded_files.csv`;
- повторный запуск не должен без необходимости копировать уже существующие файлы;
- обработка типов, пропусков и дубликатов выполняется в `02_data_preparation.ipynb`;
- объединение платформ выполняется в `03_data_integration.ipynb`.

Основные источники для дальнейшей обработки:
- Steam Games Dataset (`games.json`);
- RAWG (`videogames_data.jsonl`);
- Steam Reviews;
- Steam Recommendations;
- Steam Monthly Players;
- Twitch Evolution;
- Epic Games Store.

## Импорты

In [3]:
!pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in c:\users\245108\appdata\roaming\python\python313\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\245108\appdata\roaming\python\python313\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\programdata\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [4]:
import os
import json
import shutil
from pathlib import Path
from zipfile import ZipFile

import pandas as pd
import kagglehub

In [5]:
PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DIR = PROJECT_ROOT / "raw"

RAW_DIR.mkdir(parents=True, exist_ok=True)

print(f"Project root: {PROJECT_ROOT}")
print(f"Raw data directory: {RAW_DIR}")

Project root: C:\Users\245108\Desktop\gaming-data-analysis
Raw data directory: C:\Users\245108\Desktop\gaming-data-analysis\raw

## Список kaggle-источников

In [6]:
KAGGLE_DATASETS = {
    "twitch_streamers": {
        "handle": "hibrahimag1/top-1000-twitch-streamers-data-may-2024",
        "raw_dir": "twitch/streamers",
        "description": "Top 1000 Twitch streamers, May 2024",
    },

    "steam_games_fronkongames": {
        "handle": "fronkongames/steam-games-dataset",
        "raw_dir": "steam/fronkongames",
        "description": "Steam games dataset; games.json is the required source file",
    },

    "epic_games": {
        "handle": "ramjasmaurya/epic-games-store",
        "raw_dir": "epic",
        "description": "Epic Games Store games",
    },

    "rawg_games": {
        "handle": "atalaydenknalbant/rawg-games-dataset",
        "raw_dir": "rawg",
        "description": "RAWG games dataset",
    },

    "ultimate_games": {
        "handle": "rudrakumargupta/ultimate-games-dataset-15k-games-43-features",
        "raw_dir": "games/ultimate_games",
        "description": "Ultimate Games Dataset — 15K games, 43 features",
    },

    "twitch_evolution": {
        "handle": "rankirsh/evolution-of-top-games-on-twitch",
        "raw_dir": "twitch/evolution",
        "description": "Evolution of top games on Twitch",
    },

    "metacritic_vs_steam": {
        "handle": "alyahmedts13/top-pc-games-metacritic-vs-steam-popularity",
        "raw_dir": "steam/metacritic_vs_steam",
        "description": "Metacritic scores vs Steam popularity",
    },

    "steam_games_2025": {
        "handle": "abhishekgupta56447/steam-games-dataset-2025",
        "raw_dir": "steam/games_2025",
        "description": "Steam Games Dataset 2025",
    },

    "steam_games_2021_2025": {
        "handle": "jypenpen54534/steam-games-dataset-2021-2025-65k",
        "raw_dir": "steam/games_2021_2025",
        "description": "Steam Games Dataset 2021–2025",
    },

    "steam_monthly_players": {
        "handle": "lunthu/steam-monthly-average-players",
        "raw_dir": "steam/monthly_players",
        "description": "Steam monthly average players",
    },

    "steam_recommendations": {
        "handle": "antonkozyriev/game-recommendations-on-steam",
        "raw_dir": "steam/recommendations",
        "description": "Steam game recommendations",
    },

    "steam_games_artemiloff": {
        "handle": "artermiloff/steam-games-dataset",
        "raw_dir": "steam/games_artemiloff",
        "description": "Steam games dataset",
    },

    "steam_reviews": {
        "handle": "andrewmvd/steam-reviews",
        "raw_dir": "steam/reviews",
        "description": "Steam reviews",
    },
}

In [7]:
def download_kaggle_dataset(dataset_info):
    """
    Загружает Kaggle dataset через kagglehub.

    Возвращает путь к каталогу, в который Kagglehub
    поместил скачанные файлы.
    """
    
    handle = dataset_info["handle"]
    
    print("=" * 80)
    print(f"Downloading: {handle}")
    
    try:
        dataset_path = kagglehub.dataset_download(handle)
        
        print(f"Downloaded to: {dataset_path}")
        return Path(dataset_path)
    
    except Exception as e:
        print(f"ERROR while downloading {handle}")
        print(f"{type(e).__name__}: {e}")
        print()
        print(
            "Если ошибка связана с авторизацией Kaggle, "
            "проверь Kaggle API credentials."
        )
        
        return None

## Копирование в /raw

In [37]:
def copy_dataset_to_raw(source_path, dataset_info):
    """
    Копирует содержимое загруженного Kaggle dataset
    в структуру raw/ проекта.
    """
    
    if source_path is None:
        return None
    
    destination = RAW_DIR / dataset_info["raw_dir"]
    destination.mkdir(parents=True, exist_ok=True)
    
    copied_files = []
    
    for source_file in source_path.rglob("*"):
        if not source_file.is_file():
            continue
        
        relative_path = source_file.relative_to(source_path)
        destination_file = destination / relative_path
        
        destination_file.parent.mkdir(
            parents=True,
            exist_ok=True
        )
        
        if (
            destination_file.exists()
            and destination_file.stat().st_size == source_file.stat().st_size
        ):
            copied_files.append(destination_file)
            continue

        shutil.copy2(source_file, destination_file)
        copied_files.append(destination_file)
    
    print(f"Copied {len(copied_files)} files to:")
    print(destination)
    
    return destination

## Загрузка датасетов

In [9]:
downloaded_datasets = {}
for name, dataset_info in KAGGLE_DATASETS.items():
    
    dataset_path = download_kaggle_dataset(dataset_info)
    
    if dataset_path is not None:
        raw_path = copy_dataset_to_raw(
            dataset_path,
            dataset_info
        )
        
        downloaded_datasets[name] = {
            "kaggle_path": dataset_path,
            "raw_path": raw_path,
        }

================================================================================
Downloading: hibrahimag1/top-1000-twitch-streamers-data-may-2024
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\hibrahimag1\top-1000-twitch-streamers-data-may-2024\versions\3
Copied 1 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\twitch\streamers
================================================================================
Downloading: fronkongames/steam-games-dataset
Downloading to C:\Users\245108\.cache\kagglehub\datasets\fronkongames\steam-games-dataset\54.archive...

100%|███████████████████████████████████████████████████████████████████████████████| 305M/305M [00:08<00:00, 36.3MB/s]

Extracting files...

Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\fronkongames\steam-games-dataset\versions\54
Copied 2 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\fronkongames
================================================================================
Downloading: ramjasmaurya/epic-games-store
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\ramjasmaurya\epic-games-store\versions\14
Copied 4 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\epic
================================================================================
Downloading: atalaydenknalbant/rawg-games-dataset
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\atalaydenknalbant\rawg-games-dataset\versions\4
Copied 3 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\rawg
================================================================================
Downloading: rudrakumargupta/ultimate-games-dataset-15k-games-43-features
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\rudrakumargupta\ultimate-games-dataset-15k-games-43-features\versions\1
Copied 1 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\games\ultimate_games
================================================================================
Downloading: rankirsh/evolution-of-top-games-on-twitch
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\rankirsh\evolution-of-top-games-on-twitch\versions\17
Copied 2 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\twitch\evolution
================================================================================
Downloading: alyahmedts13/top-pc-games-metacritic-vs-steam-popularity
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\alyahmedts13\top-pc-games-metacritic-vs-steam-popularity\versions\2
Copied 4 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\metacritic_vs_steam
================================================================================
Downloading: abhishekgupta56447/steam-games-dataset-2025
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\abhishekgupta56447\steam-games-dataset-2025\versions\1
Copied 13 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025
================================================================================
Downloading: jypenpen54534/steam-games-dataset-2021-2025-65k
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\jypenpen54534\steam-games-dataset-2021-2025-65k\versions\4
Copied 2 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2021_2025
================================================================================
Downloading: lunthu/steam-monthly-average-players
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\lunthu\steam-monthly-average-players\versions\2
Copied 1 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\monthly_players
================================================================================
Downloading: antonkozyriev/game-recommendations-on-steam
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\antonkozyriev\game-recommendations-on-steam\versions\28
Copied 4 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\recommendations
================================================================================
Downloading: artermiloff/steam-games-dataset
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\artermiloff\steam-games-dataset\versions\2
Copied 4 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_artemiloff
================================================================================
Downloading: andrewmvd/steam-reviews
Downloaded to: C:\Users\245108\.cache\kagglehub\datasets\andrewmvd\steam-reviews\versions\3
Copied 1 files to:
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\reviews

In [14]:
def list_files(path):
    """
    Возвращает список всех файлов внутри директории.
    """
    
    path = Path(path)
    
    return [
        file
        for file in path.rglob("*")
        if file.is_file()
    ]

In [15]:
for name, info in downloaded_datasets.items():
    
    print("=" * 80)
    print(name)
    
    files = list_files(info["raw_path"])
    
    for file in files:
        size_mb = file.stat().st_size / (1024 ** 2)
        print(f"{file.name:60} {size_mb:10.2f} MB")

================================================================================
twitch_streamers
datasetV2.csv                                                      0.12 MB
================================================================================
steam_games_fronkongames
games.csv                                                        382.56 MB
games.json                                                       925.28 MB
================================================================================
epic_games
epic games store-video games.csv                                   0.25 MB
epic-games-apps.csv                                                0.00 MB
epic-games-demo.csv                                                0.01 MB
epic_games_editor.csv                                              0.01 MB
================================================================================
rawg_games
videogames_data.csv                                             1907.80 MB
videogames_data.parquet                                          964.80 MB
videogames_data.jsonl                                           4101.47 MB
================================================================================
ultimate_games
Ultimate_Games_Dataset.csv                                        27.54 MB
================================================================================
twitch_evolution
Twitch_game_data.csv                                               1.56 MB
Twitch_global_data.csv                                             0.01 MB
================================================================================
metacritic_vs_steam
metacritic_Toppc_games.csv                                         3.60 MB
metacritic_Toppc_games_clean.csv                                   3.53 MB
steam_spy_data.csv                                                 1.15 MB
steam_spy_data_clean.csv                                           1.23 MB
================================================================================
steam_games_2025
applications.csv                                                 171.74 MB
application_categories.csv                                        11.84 MB
application_developers.csv                                         3.27 MB
application_genres.csv                                             6.21 MB
application_platforms.csv                                          3.11 MB
application_publishers.csv                                         2.90 MB
categories.csv                                                     0.01 MB
developers.csv                                                     1.97 MB
genres.csv                                                         0.00 MB
MANIFEST.json                                                      0.00 MB
platforms.csv                                                      0.00 MB
publishers.csv                                                     1.68 MB
reviews.csv                                                      638.78 MB
================================================================================
steam_games_2021_2025
a_steam_data_2021_2025.csv                                        11.11 MB
collect_data_v2.py                                                 0.01 MB
================================================================================
steam_monthly_players
steamcharts.csv                                                   36.13 MB
================================================================================
steam_recommendations
games.csv                                                          4.64 MB
games_metadata.json                                               16.74 MB
recommendations.csv                                             1929.50 MB
users.csv                                                        184.12 MB
================================================================================
steam_games_artemiloff
games_march2025_cleaned.csv                                      446.93 MB
games_march2025_full.csv                                         449.65 MB
games_may2024_cleaned.csv                                        402.75 MB
games_may2024_full.csv                                           405.23 MB
================================================================================
steam_reviews
dataset.csv                                                     2060.77 MB

## Отдельная работа с games.json от fronkongames обусловлена его большим размером и надобностью понять его структуру

In [12]:
%pip install ijson

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ijson in c:\users\245108\appdata\roaming\python\python313\site-packages (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import ijson
from pathlib import Path

fronko_path = downloaded_datasets["steam_games_fronkongames"]["raw_path"]
games_json_files = list(fronko_path.rglob("games.json"))
games_json = games_json_files[0]

with games_json.open("rb") as f:
    app_id, game = next(ijson.kvitems(f, ""))

print("AppID:", app_id)
print("Количество полей:", len(game))
print("\nПоля игры:")
print(list(game.keys()))

print("\nПример значений:")
for key in list(game.keys())[:10]:
    print(f"{key}: {str(game[key])[:150]}")

AppID: 2539430
Количество полей: 42

Поля игры:
['name', 'release_date', 'required_age', 'price', 'dlc_count', 'detailed_description', 'about_the_game', 'short_description', 'reviews', 'header_image', 'website', 'support_url', 'support_email', 'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url', 'achievements', 'recommendations', 'notes', 'supported_languages', 'full_audio_languages', 'packages', 'developers', 'publishers', 'categories', 'genres', 'screenshots', 'movies', 'user_score', 'score_rank', 'positive', 'negative', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'discount', 'peak_ccu', 'tags']

Пример значений:
name: Black Dragon Mage Playtest
release_date: Aug 1, 2023
required_age: 0
price: 0.0
dlc_count: 0
detailed_description:
about_the_game:
short_description:
reviews:
header_image: https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2539430/header.jpg?t=1699268702

In [24]:
import ijson
from collections import Counter

game_count = 0
field_counts = Counter()
first_app_ids = []

with games_json.open("rb") as f:
    for app_id, game in ijson.kvitems(f, ""):
        game_count += 1
        field_counts.update(game.keys())

        if len(first_app_ids) < 10:
            first_app_ids.append(app_id)

print(f"Всего игр: {game_count:,}")
print("Первые AppID:", first_app_ids)

print("\nНаиболее распространённые поля:")
for field, count in field_counts.most_common(20):
    print(f"{field}: {count:,} игр")

Всего игр: 144,499
Первые AppID: ['2539430', '496350', '1034400', '3292190', '3631080', '1654170', '1934300', '700340', '1157670', '1540330']

Наиболее распространённые поля:
name: 144,499 игр
release_date: 144,499 игр
required_age: 144,499 игр
price: 144,499 игр
dlc_count: 144,499 игр
detailed_description: 144,499 игр
about_the_game: 144,499 игр
short_description: 144,499 игр
reviews: 144,499 игр
header_image: 144,499 игр
website: 144,499 игр
support_url: 144,499 игр
support_email: 144,499 игр
windows: 144,499 игр
mac: 144,499 игр
linux: 144,499 игр
metacritic_score: 144,499 игр
metacritic_url: 144,499 игр
achievements: 144,499 игр
recommendations: 144,499 игр

## Общий каталог файлов

In [25]:
def get_file_type(file_path):
    """
    Определяет тип файла по расширению.
    """
    
    suffix = Path(file_path).suffix.lower()
    
    mapping = {
        ".csv": "CSV",
        ".json": "JSON",
        ".jsonl": "JSON Lines",
        ".parquet": "Parquet",
        ".xlsx": "Excel",
        ".xls": "Excel",
        ".xml": "XML",
        ".txt": "Text",
    }
    
    return mapping.get(suffix, suffix.upper())

In [26]:
def get_file_size_mb(file_path):
    return Path(file_path).stat().st_size / (1024 ** 2)

In [27]:
file_catalog = []

for dataset_name, info in downloaded_datasets.items():
    
    for file in list_files(info["raw_path"]):
        
        file_catalog.append({
            "dataset": dataset_name,
            "file": file.name,
            "path": str(file),
            "type": get_file_type(file),
            "size_mb": round(get_file_size_mb(file), 2),
        })

file_catalog_df = pd.DataFrame(file_catalog)

file_catalog_df.sort_values(
    ["dataset", "file"]
).reset_index(drop=True)

,dataset,file,path,type,size_mb
0,epic_games,epic games store-video games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.25
1,epic_games,epic-games-apps.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00
2,epic_games,epic-games-demo.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
3,epic_games,epic_games_editor.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
4,metacritic_vs_steam,metacritic_Toppc_games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.60
5,metacritic_vs_steam,metacritic_Toppc_games_clean.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.53
6,metacritic_vs_steam,steam_spy_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.15
7,metacritic_vs_steam,steam_spy_data_clean.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.23
8,rawg_games,videogames_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1907.80
9,rawg_games,videogames_data.jsonl,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON Lines,4101.47
10,rawg_games,videogames_data.parquet,C:\Users\245108\Desktop\gaming-data-analysis\r...,Parquet,964.80
11,steam_games_2021_2025,a_steam_data_2021_2025.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,11.11
12,steam_games_2021_2025,collect_data_v2.py,C:\Users\245108\Desktop\gaming-data-analysis\r...,.PY,0.01
13,steam_games_2025,MANIFEST.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,0.00
14,steam_games_2025,application_categories.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,11.84
15,steam_games_2025,application_developers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.27
16,steam_games_2025,application_genres.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,6.21
17,steam_games_2025,application_platforms.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.11
18,steam_games_2025,application_publishers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,2.90
19,steam_games_2025,applications.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,171.74
20,steam_games_2025,categories.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
21,steam_games_2025,developers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.97
22,steam_games_2025,genres.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00
23,steam_games_2025,platforms.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00
24,steam_games_2025,publishers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.68
25,steam_games_2025,reviews.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,638.78
26,steam_games_artemiloff,games_march2025_cleaned.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,446.93
27,steam_games_artemiloff,games_march2025_full.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,449.65
28,steam_games_artemiloff,games_may2024_cleaned.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,402.75
29,steam_games_artemiloff,games_may2024_full.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,405.23
30,steam_games_fronkongames,games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,382.56
31,steam_games_fronkongames,games.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,925.28
32,steam_monthly_players,steamcharts.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,36.13
33,steam_recommendations,games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,4.64
34,steam_recommendations,games_metadata.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,16.74
35,steam_recommendations,recommendations.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1929.50
36,steam_recommendations,users.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,184.12
37,steam_reviews,dataset.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,2060.77
38,twitch_evolution,Twitch_game_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.56
39,twitch_evolution,Twitch_global_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
40,twitch_streamers,datasetV2.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.12
41,ultimate_games,Ultimate_Games_Dataset.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,27.54

In [38]:
from datetime import datetime, timezone

manifest = file_catalog_df.copy()

manifest["collected_at_utc"] = datetime.now(
    timezone.utc
).isoformat()

manifest["source_type"] = "kaggle_dataset"

manifest.to_csv(
    PROJECT_ROOT / "docs" / "downloaded_files.csv",
    index=False,
    encoding="utf-8-sig",
)

display(manifest.head())
print(f"Записано файлов в манифест: {len(manifest)}")

,dataset,file,path,type,size_mb,collected_at_utc,source_type
0,twitch_streamers,datasetV2.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.12,2026-10-19T09:27:03.314978+00:00,kaggle_dataset
1,steam_games_fronkongames,games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,382.56,2026-10-19T09:27:03.314978+00:00,kaggle_dataset
2,steam_games_fronkongames,games.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,925.28,2026-10-19T09:27:03.314978+00:00,kaggle_dataset
3,epic_games,epic games store-video games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.25,2026-10-19T09:27:03.314978+00:00,kaggle_dataset
4,epic_games,epic-games-apps.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00,2026-10-19T09:27:03.314978+00:00,kaggle_dataset

Записано файлов в манифест: 42

## Профилирование csv и json

In [28]:
def profile_csv(file_path, nrows=1000):
    """
    Быстрый профиль CSV-файла.
    Читается только nrows строк.
    """
    
    file_path = Path(file_path)
    
    try:
        df = pd.read_csv(
            file_path,
            nrows=nrows,
            low_memory=False
        )
        
        profile = {
            "file": file_path.name,
            "rows_sampled": len(df),
            "columns": len(df.columns),
            "column_names": list(df.columns),
            "dtypes": df.dtypes.astype(str).to_dict(),
        }
        
        return profile, df
    
    except Exception as e:
        print(f"Could not read {file_path}")
        print(f"{type(e).__name__}: {e}")
        return None, None

In [29]:
def profile_json(file_path, nrows=1000):
    """
    Пытается определить структуру JSON.
    """
    
    file_path = Path(file_path)
    
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        if isinstance(data, list):
            sample = data[:nrows]
            structure = "list"
            rows = len(data)
        
        elif isinstance(data, dict):
            sample = data
            structure = "dict"
            rows = len(data)
        
        else:
            sample = data
            structure = type(data).__name__
            rows = None
        
        return {
            "file": file_path.name,
            "structure": structure,
            "rows": rows,
            "sample": sample,
        }
    
    except Exception as e:
        print(f"Could not read JSON: {file_path}")
        print(f"{type(e).__name__}: {e}")
        return None

In [30]:
csv_files = [
    Path(row["path"])
    for _, row in file_catalog_df.iterrows()
    if row["type"] == "CSV"
]

print(f"Found {len(csv_files)} CSV files")

Found 36 CSV files

In [31]:
for file in csv_files:
    
    print("=" * 100)
    print(file)
    
    profile, sample = profile_csv(file, nrows=5)
    
    if sample is not None:
        print(f"Columns: {len(sample.columns)}")
        print(sample.columns.tolist())
        display(sample.head())

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\twitch\streamers\datasetV2.csv
Columns: 17
['RANK', 'NAME', 'LANGUAGE', 'TYPE', 'MOST_STREAMED_GAME', '2ND_MOST_STREAMED_GAME', 'AVERAGE_STREAM_DURATION', 'FOLLOWERS_GAINED_PER_STREAM', 'AVG_VIEWERS_PER_STREAM', 'AVG_GAMES_PER_STREAM', 'TOTAL_TIME_STREAMED', 'TOTAL_FOLLOWERS', 'TOTAL_VIEWS', 'TOTAL_GAMES_STREAMED', 'ACTIVE_DAYS_PER_WEEK', 'MOST_ACTIVE_DAY', 'DAY_WITH_MOST_FOLLOWERS_GAINED']

,RANK,NAME,LANGUAGE,TYPE,MOST_STREAMED_GAME,2ND_MOST_STREAMED_GAME,AVERAGE_STREAM_DURATION,FOLLOWERS_GAINED_PER_STREAM,AVG_VIEWERS_PER_STREAM,AVG_GAMES_PER_STREAM,TOTAL_TIME_STREAMED,TOTAL_FOLLOWERS,TOTAL_VIEWS,TOTAL_GAMES_STREAMED,ACTIVE_DAYS_PER_WEEK,MOST_ACTIVE_DAY,DAY_WITH_MOST_FOLLOWERS_GAINED
0,1,kaicenat,English,personality,Just Chatting,I'm Only Sleeping,7.6,18405,15852,2.3,4698,10600000,9150000,194,3.6,Friday,Saturday
1,2,jynxzi,English,personality,Tom Clancy's Rainbow Six Siege,NBA 2K20,5.4,3386,1145,1.2,8407,5760000,1950000,54,5.6,Tuesday,Sunday
2,3,caedrel,English,personality,League of Legends,I'm Only Sleeping,6.3,689,12331,1.3,6728,797000,14200000,111,2.8,Thursday,Sunday
3,4,caseoh_,English,personality,NBA 2K23,Just Chatting,4.6,7185,0,3.6,2554,4220000,53,385,6.2,Friday,Monday
4,5,ibai,Spanish,personality,Just Chatting,League of Legends,4.1,8289,190714,1.5,6865,15600000,359000000,149,4.3,Wednesday,Saturday

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\fronkongames\games.csv
Columns: 39
['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\epic\epic games store-video games.csv
Columns: 17
['game_link', 'name', 'price of game', 'developer of game', 'genres of games', 'features of game', 'publisher of game', 'date release', 'recommended_os', 'cpu', 'memory', 'gpu_x', 'storage', 'Critics Recommend', 'OpenCritic Rating', 'platform', 'Top Critic Average']

,game_link,name,price of game,developer of game,genres of games,features of game,publisher of game,date release,recommended_os,cpu,memory,gpu_x,storage,Critics Recommend,OpenCritic Rating,platform,Top Critic Average
0,"HITMAN - Game of the Year Edition₹3,249",HITMAN - Game of the Year Edition,"₹3,249",IO Interactive A/S,ActionAction-AdventureShooterStealth,Single Player,IO Interactive A/S,09/03/20,OS 64-bit Windows 7 / 64-bit Windows 8 (8.1) o...,"Intel CPU Core i7 3770 3,4 GHz / AMD CPU AMD F...",8,Nvidia GPU GeForce GTX 770 / AMD GPU Radeon R9...,50,92%,Mighty,Windows,84.0
1,"The Medium₹2,949",The Medium,"₹2,949",Bloober Team,HorrorAdventure,Single Player,Bloober Team S.A.,01/28/21,Windows 10 (64bit version only),Intel® Core™ i5-9600 / AMD Ryzen™ 7 3700X,16,@1080p NVIDIA GeForce® GTX 1060 6GB / AMD Rade...,30,63%,Strong,PlatformWindowsWindows,75.0
2,Into the Breach₹446,Into The Breach,₹446,Subset Games,Turn-BasedRogue-LiteStrategy,Single Player,Subset Games,02/27/18,Windows 7+,1.7 GHz,1 GB,NaN,250 MB,90%,Mighty,PlatformWindowsWindowsMac OSMac OS,88.0
3,The Lion's Song₹189,The Lion's Song,₹189,Mi'pu'mi Games,NarrationAdventure,Single Player,Mi'pu'mi Games,05/13/21,Windows 7 / 8 / 10,2 GHZ,1 GB RAM,DirectX 10 compatible,500 MB available space,80%,Strong,PlatformWindowsWindowsMac OSMac OS,81.0
4,Costume Quest₹297,Costume Quest,₹297,Double Fine Productions,RPGAdventure,Single Player,Double Fine Productions,10/19/10,Windows 7 or higher,2.2 GHz dual core CPU,1 GB RAM,NaN,"256 MB GeForce 220, Radeon 4550, Intel HD 3000...",NaN,NaN,PlatformWindowsWindows,NaN

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\epic\epic-games-apps.csv
Columns: 16
['links', 'name', 'type', 'genres', 'features', 'price', 'developer', 'publisher', 'release_date', 'platform', 'os requirements', 'processor required', 'memory', 'storage', 'direct x', 'languages supported']

,links,name,type,genres,features,price,developer,publisher,release_date,platform,os requirements,processor required,memory,storage,direct x,languages supported
0,Opera GX - The First Browser for GamersFree,Opera GX - The First Browser for Gamers,Software,NaN,NaN,Free,DeveloperOpera GX,PublisherOpera GX,Release Date01/25/22,Initial Release06/11/19,Windows 7+,2Ghz,2GB,NaN,NaN,"AUDIO: EnglishTEXT: Arabic, English, Chinese -..."
1,DiscordFree,Discord,Software,NaN,NaN,Free,DeveloperDiscord,PublisherDiscord,Release Date06/10/21,Initial Release05/13/15,Windows 7 and above,2GHz,4 GB RAM,NaN,NaN,"AUDIO: English | TEXT: English, French, German..."
2,HumbleFree,Humble,Software,NaN,NaN,Free,DeveloperHumble,PublisherHumble,Release Date02/10/22,PlatformWindowsWindows,Windows 7,Intel Pentium 4,1GB,300MB,NaN,Audio: EnglishText: English
3,KenShape₹89,KenShape,Software,NaN,NaN,₹89,DeveloperKenney,PublisherKenney,Release Date04/22/21,Initial Release02/24/21,Windows 7 (SP1+),3.0 GHz Dual Core Processor,2 GB RAM,DirectX 10,NaN,English
4,Beyond TypicalsFree,Beyond Typicals,Software,Simulation,Single Player,Free,DeveloperBeyond CAD,PublisherBeyond CAD,Release Date03/24/22,Platform,Windows 10 64 bit,"Quad-core Intel or AMD, 2.5 GHz or faster",4 GB RAM,6 GB,DirectX 11,AUDIO: EnglishTEXT: English

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\epic\epic-games-demo.csv
Columns: 17
['links', 'name', 'type', 'genres', 'features', 'Developer', 'publisher', 'release date', 'initial release in windows', 'os recommended', 'cpu', 'memory', 'gpu', 'directx', 'storage', 'language', 'price']

,links,name,type,genres,features,Developer,publisher,release date,initial release in windows,os recommended,cpu,memory,gpu,directx,storage,language,price
0,System Shock Demo,System Shock,Base Game,Horror,Single Player,Nightdive Studios,Prime Matter,AvailableComing Soon,PlatformWindowsWindows,Windows 7 Service Pack 1 (64-Bit),Intel Core i5-2400/AMD FX-8320,4GB,8GB,DirectX 11,NVIDIA GTX 670/AMD Radeon HD 7870,NaN,₹959
1,Read Only Memories: NEURODIVER Pilot Memory,Read Only Memories: NEURODIVER,Base Game,Indie,Single Player,"MidBoss, LLC.","MidBoss, LLC.",AvailableComing Soon,PlatformWindowsWindowsMac OSMac OS,Windows 7 SP1+,1.1+ GHz Processor,2GB,"MidBoss, LLC.",10,Graphics card with DX10 (shader model 4.0) cap...,NaN,NaN
2,Crying Suns Demo,Demo,Demo,NaN,Achievements,Alt Shift,Humble Games,NaN,Initial Release09/18/19,Windows 7,Dual-core 2.5 GHz or equivalent,4 GB,2 GB,10,"Dedicated GPU, 1 GB VRAM/ AMD HD5750 or equiva...",NaN,NaN
3,Against The Storm- Royal Woodlands Demo,Against the Storm- Royal Woodlands Demo,Demo,NaN,NaN,Eremite Games,Eremite Games,NaN,Platform,Microsoft Windows 7/8,Intel i5,8GB,TBC,NaN,NaN,NaN,NaN
4,Ghostrunner Demo,Ghostrunner Demo,Demo,ActionStrategyStealth,Single Player,One More Level and 3D Realms,505 Games,NaN,PlatformWindowsWindows,WIN7-64 bit,Intel i3-2100 / AMD A8-5600k,8 GB RAM,GeForce GTX 630 / Radeon HD 6570,NaN,NaN,NaN,NaN

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\epic\epic_games_editor.csv
Columns: 20
['links', 'name', 'type', 'genres', 'features', 'Developer', 'publisher', 'release date', 'platform', 'os recommended', 'cpu', 'memory', 'gpu', 'directx', 'storage', 'language', 'price', 'Critics Recommend', 'Top Critic Average', 'OpenCritic Rating']

,links,name,type,genres,features,Developer,publisher,release date,platform,os recommended,cpu,memory,gpu,directx,storage,language,price,Critics Recommend,Top Critic Average,OpenCritic Rating
0,Helium RainFree,Helium Rain,Editor,–,–,CREATIVE ASSEMBLY,Deimos Games,03/01/19,Platform,Windows 7 (64 bits),Intel Core® i3,NVIDIA GeForce® GTX 470 / AMD Radeon® HD 6870 ...,5 GB available space,DirectX10,4 GB RAM,NaN,Free,NaN,NaN,NaN
1,Thunder Tier One Modding ToolFree,Thunder Tier One Modding Tool,Editor,–,–,"KRAFTON, Inc.","KRAFTON, Inc.",02/23/22,PlatformWindowsWindows,Windows 7 64-bit,Intel Core i5 3.3 GHz,16 GB,NaN,NaN,NaN,AUDIO: English | TEXT: English,Free,NaN,NaN,NaN
2,Insurgency: Sandstorm - Mod Tools & EditorFree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,English,Free,61%,79.0,Strong
3,A Total War Saga: TROY – ASSEMBLY KITFree,A Total War Saga: TROY,Base Game,Strategy,MultiplayerSingle Player,CREATIVE ASSEMBLY,SEGA,Initial Release10/08/20,Windows,Windows 7/8.1/10 64 Bit,Intel Core 2 Duo 3.0 GHz/Intel i7 8550U 1.80GHz,4 GB/6 GB (It is 4 for dedicated GPU and 6 for...,Nvidia GTX 460 1GB/AMD Radeon HD 5770 1 GB/Int...,A Total War Saga: TROY - ASSEMBLY KIT,A Total War Saga: TROY - AMAZONS,Strategy,"₹2,249",68%,76.0,Strong
4,Post Scriptum Modding SDKFree,Post Scriptum Modding SDK,Editor,–,–,Periscope Games,Offworld Industries,12/03/20,PlatformWindowsWindows,Windows 7 SP1 (X64),Intel Core i or AMD Ryzen with 4 physical cores,Geforce GTX 970 or AMD Radeon RX 570 with at l...,Version 11,SDK 120GB,8GB RAM,"Audio: English, Chinese - Simplified, Chinese ...",Free,NaN,NaN,NaN

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\rawg\videogames_data.csv
Columns: 54
['id', 'slug', 'name', 'released', 'background_image', 'rating', 'rating_top', 'ratings_count', 'reviews_text_count', 'added', 'metacritic', 'playtime', 'suggestions_count', 'updated', 'reviews_count', 'saturated_color', 'dominant_color', 'platforms', 'stores', 'developers', 'genres', 'tags', 'publishers', 'esrb_rating', 'added_by_status', 'metacritic_url', 'ratings', 'clip', 'name_original', 'reddit_url', 'movies_count', 'reactions', 'background_image_additional', 'website', 'reddit_count', 'achievements_count', 'youtube_count', 'short_screenshots', 'creators_count', 'twitch_count', 'alternative_names', 'parent_achievements_count', 'additions_count', 'metacritic_platforms', 'screenshots_count', 'parent_platforms', 'game_series_count', 'description', 'description_raw', 'parents_count', 'reddit_name', 'reddit_description', 'reddit_logo', 'tba']

,id,slug,name,released,background_image,rating,rating_top,ratings_count,reviews_text_count,added,...,screenshots_count,parent_platforms,game_series_count,description,description_raw,parents_count,reddit_name,reddit_description,reddit_logo,tba
0,3498,grand-theft-auto-v,Grand Theft Auto V,2013-09-17,https://media.rawg.io/media/games/20a/20aa03a1...,4.47,5.0,7409.0,135.0,22635.0,...,55.0,PC|PlayStation|Xbox,12.0,"Rockstar Games went bigger, since their previo...","Rockstar Games went bigger, since their previo...",NaN,NaN,NaN,NaN,NaN
1,3328,the-witcher-3-wild-hunt,The Witcher 3: Wild Hunt,2015-05-18,https://media.rawg.io/media/games/618/618c2031...,4.64,5.0,7234.0,120.0,22285.0,...,107.0,PC|PlayStation|Xbox|Apple Macintosh|Nintendo,9.0,"The third game in a series, it holds nothing b...","The third game in a series, it holds nothing b...",NaN,NaN,NaN,NaN,NaN
2,4200,portal-2,Portal 2,2011-04-18,https://media.rawg.io/media/games/2ba/2bac0e87...,4.58,5.0,6118.0,57.0,20926.0,...,24.0,PC|PlayStation|Xbox|Apple Macintosh|Linux,3.0,Portal 2 is a first-person puzzle game develop...,Portal 2 is a first-person puzzle game develop...,NaN,NaN,NaN,NaN,NaN
3,4291,counter-strike-global-offensive,Counter-Strike: Global Offensive,2012-08-21,https://media.rawg.io/media/games/736/73619bd3...,3.57,4.0,3638.0,37.0,18377.0,...,22.0,PC|PlayStation|Xbox|Linux,5.0,Counter-Strike is a multiplayer phenomenon in ...,Counter-Strike is a multiplayer phenomenon in ...,NaN,NaN,NaN,NaN,NaN
4,5286,tomb-raider,Tomb Raider,2013-03-05,https://media.rawg.io/media/games/021/021c4e21...,4.06,4.0,4103.0,33.0,17841.0,...,19.0,PC|PlayStation|Xbox|Apple Macintosh,23.0,A cinematic revival of the series in its actio...,A cinematic revival of the series in its actio...,NaN,NaN,NaN,NaN,NaN

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\games\ultimate_games\Ultimate_Games_Dataset.csv
Columns: 43
['serial_no', 'game_id', 'title', 'release_date', 'release_year', 'all_genres', 'theme', 'art_style', 'view_dimension', 'game_mode', 'is_multiplayer', 'controls', 'developers', 'publishers', 'all_platforms', 'platform_count', 'esrb_rating', 'user_rating', 'metacritic', 'ratings_count', 'reviews_count', 'library_count', 'avg_playtime_hours', 'achievements_count', 'game_series_count', 'status_owned', 'status_beaten', 'status_playing', 'status_dropped', 'status_toplay', 'status_yet', 'all_tags', 'available_stores', 'cover_image_url', 'official_website', 'url_slug', 'description_clean', 'popularity_score', 'engagement_score', 'decade', 'is_multi_platform', 'rating_tier', 'metacritic_tier']

,serial_no,game_id,title,release_date,release_year,all_genres,theme,art_style,view_dimension,game_mode,...,cover_image_url,official_website,url_slug,description_clean,popularity_score,engagement_score,decade,is_multi_platform,rating_tier,metacritic_tier
0,1,3498,Grand Theft Auto V,2013-09-17,2013.0,Action,Crime,Realistic,3D,Single & Multiplayer,...,https://media.rawg.io/media/games/20a/20aa03a1...,http://www.rockstargames.com/V/,grand-theft-auto-v,"Rockstar Games went bigger, since their previo...",96.28,21.75,2010s,1,excellent,universal_acclaim
1,2,3328,The Witcher 3: Wild Hunt,2015-05-18,2015.0,Action|RPG,Fantasy,Realistic,3D,Singleplayer,...,https://media.rawg.io/media/games/618/618c2031...,https://thewitcher.com/en/witcher3,the-witcher-3-wild-hunt,"The third game in a series, it holds nothing b...",95.81,17.19,2010s,1,masterpiece,universal_acclaim
2,3,4200,Portal 2,2011-04-18,2011.0,Shooter|Puzzle,Sci-Fi,Realistic,3D,Single & Multiplayer,...,https://media.rawg.io/media/games/2ba/2bac0e87...,http://www.thinkwithportals.com/,portal-2,Portal 2 is a first-person puzzle game develop...,91.26,15.24,2010s,1,masterpiece,universal_acclaim
3,4,4291,Counter-Strike: Global Offensive,2012-08-21,2012.0,Shooter,Horror,Realistic,3D,Multiplayer,...,https://media.rawg.io/media/games/736/73619bd3...,http://blog.counter-strike.net/,counter-strike-global-offensive,Counter-Strike is a multiplayer phenomenon in ...,73.56,8.79,2010s,1,good,generally_favorable
4,5,5286,Tomb Raider (2013),2013-03-05,2013.0,Action,Adventure,Realistic,3D,Single & Multiplayer,...,https://media.rawg.io/media/games/021/021c4e21...,http://www.tombraider.com,tomb-raider,A cinematic revival of the series in its actio...,76.54,13.77,2010s,1,excellent,generally_favorable

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\twitch\evolution\Twitch_game_data.csv
Columns: 12
['Rank', 'Game', 'Month', 'Year', 'Hours_watched', 'Hours_streamed', 'Peak_viewers', 'Peak_channels', 'Streamers', 'Avg_viewers', 'Avg_channels', 'Avg_viewer_ratio']

,Rank,Game,Month,Year,Hours_watched,Hours_streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,1,League of Legends,1,2016,94377226,1362044,530270,2903,129172,127021,1833,69.29
1,2,Counter-Strike: Global Offensive,1,2016,47832863,830105,372654,2197,120849,64378,1117,57.62
2,3,Dota 2,1,2016,45185893,433397,315083,1100,44074,60815,583,104.26
3,4,Hearthstone,1,2016,39936159,235903,131357,517,36170,53749,317,169.29
4,5,Call of Duty: Black Ops III,1,2016,16153057,1151578,71639,3620,214054,21740,1549,14.03

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\twitch\evolution\Twitch_global_data.csv
Columns: 9
['year', 'Month', 'Hours_watched', 'Avg_viewers', 'Peak_viewers', 'Streams', 'Avg_channels', 'Games_streamed', 'Viewer_ratio']

,year,Month,Hours_watched,Avg_viewers,Peak_viewers,Streams,Avg_channels,Games_streamed,Viewer_ratio
0,2016,1,480241904,646355,1275257,7701675,20076,12149,29.08
1,2016,2,441859897,635769,1308032,7038520,20427,12134,28.98
2,2016,3,490669308,660389,1591551,7390957,20271,12234,28.92
3,2016,4,377975447,525696,1775120,6869719,16791,12282,28.80
4,2016,5,449836631,605432,1438962,7535519,19394,12424,28.85

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\metacritic_vs_steam\metacritic_Toppc_games.csv
Columns: 5
['Name', 'Release_Date', 'Rating', 'Description', 'Score']

,Name,Release_Date,Rating,Description,Score
0,Disco Elysium: The Final Cut,"Mar 30, 2021",M,Disco Elysium - The Final Cut is the definitiv...,97 Metascore
1,Half-Life 2,"Nov 16, 2004",M,[Metacritic's 2004 PC Game of the Year] By ta...,96 Metascore
2,Grand Theft Auto V,"Apr 13, 2015",M,"Los Santos is a vast, sun-soaked metropolis fu...",96 Metascore
3,Baldur's Gate 3,"Aug 3, 2023",M,"An ancient evil has returned to Baldur's Gate,...",96 Metascore
4,The Orange Box,"Oct 10, 2007",M,Games included in The Orange Box compilation: ...,96 Metascore

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\metacritic_vs_steam\metacritic_Toppc_games_clean.csv
Columns: 5
['Name', 'release_Date', 'Rating', 'Description', 'score']

,Name,release_Date,Rating,Description,score
0,Disco Elysium: The Final Cut,2021-03-30,M,Disco Elysium - The Final Cut is the definitiv...,97
1,Half-Life 2,2004-11-16,M,[Metacritic's 2004 PC Game of the Year] By ta...,96
2,Grand Theft Auto V,2015-04-13,M,"Los Santos is a vast, sun-soaked metropolis fu...",96
3,Baldur's Gate 3,2023-08-03,M,"An ancient evil has returned to Baldur's Gate,...",96
4,The Orange Box,2007-10-10,M,Games included in The Orange Box compilation: ...,96

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\metacritic_vs_steam\steam_spy_data.csv
Columns: 17
['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu']

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,730,Counter-Strike: Global Offensive,Valve,Valve,NaN,7642084,1173003,0,"100,000,000 .. 200,000,000",34112,731,6777,297,0,0,0,1013936
1,1172470,Apex Legends,Respawn,Electronic Arts,NaN,668053,326926,0,"100,000,000 .. 200,000,000",11025,635,977,256,0,0,0,124262
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",NaN,1520457,1037487,0,"100,000,000 .. 200,000,000",23333,820,5899,335,0,0,0,314682
3,1623730,Palworld,Pocketpair,Pocketpair,NaN,358266,22443,0,"50,000,000 .. 100,000,000",3930,770,2223,397,2249,2999,25,18028
4,440,Team Fortress 2,Valve,Valve,NaN,1044264,117208,0,"50,000,000 .. 100,000,000",21058,772,4175,161,0,0,0,43819

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\metacritic_vs_steam\steam_spy_data_clean.csv
Columns: 16
['appid', 'Name', 'developer', 'publisher', 'positive', 'negative', 'owners_range', 'average_playTime_total', 'average_playTime_2weeks', 'median_playTime_total', 'median_platyime_2weeks', 'price_USD', 'initialprice_USD', 'discount_%', 'peak_Current_Players_yesterday', 'estimated_owners']

,appid,Name,developer,publisher,positive,negative,owners_range,average_playTime_total,average_playTime_2weeks,median_playTime_total,median_platyime_2weeks,price_USD,initialprice_USD,discount_%,peak_Current_Players_yesterday,estimated_owners
0,730,Counter-Strike: Global Offensive,Valve,Valve,7642084,1173003,"100,000,000 .. 200,000,000",34112,731,6777,297,0.00,0.00,0,1013936,150000000
1,1172470,Apex Legends,Respawn,Electronic Arts,668053,326926,"100,000,000 .. 200,000,000",11025,635,977,256,0.00,0.00,0,124262,150000000
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",1520457,1037487,"100,000,000 .. 200,000,000",23333,820,5899,335,0.00,0.00,0,314682,150000000
3,1623730,Palworld,Pocketpair,Pocketpair,358266,22443,"50,000,000 .. 100,000,000",3930,770,2223,397,22.49,29.99,25,18028,75000000
4,440,Team Fortress 2,Valve,Valve,1044264,117208,"50,000,000 .. 100,000,000",21058,772,4175,161,0.00,0.00,0,43819,75000000

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\applications.csv
Columns: 30
['appid', 'name', 'type', 'is_free', 'release_date', 'required_age', 'short_description', 'supported_languages', 'header_image', 'background', 'metacritic_score', 'recommendations_total', 'mat_supports_windows', 'mat_supports_mac', 'mat_supports_linux', 'mat_initial_price', 'mat_final_price', 'mat_discount_percent', 'mat_currency', 'mat_achievement_count', 'mat_pc_os_min', 'mat_pc_processor_min', 'mat_pc_memory_min', 'mat_pc_graphics_min', 'mat_pc_os_rec', 'mat_pc_processor_rec', 'mat_pc_memory_rec', 'mat_pc_graphics_rec', 'created_at', 'updated_at']

,appid,name,type,is_free,release_date,required_age,short_description,supported_languages,header_image,background,...,mat_pc_os_min,mat_pc_processor_min,mat_pc_memory_min,mat_pc_graphics_min,mat_pc_os_rec,mat_pc_processor_rec,mat_pc_memory_rec,mat_pc_graphics_rec,created_at,updated_at
0,10,Counter-Strike,game,False,2000-11-01,0,Play the world's number 1 online action game. ...,"English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
1,20,Team Fortress Classic,game,False,1999-04-01,0,One of the most popular online action games of...,"English, French, German, Italian, Spanish - Sp...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
2,30,Day of Defeat,game,False,2003-05-01,0,Enlist in an intense brand of Axis vs. Allied ...,"English, French, German, Italian, Spanish - Spain",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
3,40,Deathmatch Classic,game,False,2001-06-01,0,Enjoy fast-paced multiplayer gaming with Death...,"English, French, German, Italian, Spanish - Sp...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
4,50,Half-Life: Opposing Force,game,False,1999-11-01,0,Return to the Black Mesa Research Facility as ...,"English, French, German, Korean",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\application_categories.csv
Columns: 2
['appid', 'category_id']

   appid  category_id
0     10           72
1     10           90
2     10          130
3     10          133
4     10          193

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\application_developers.csv
Columns: 2
['appid', 'developer_id']

   appid  developer_id
0     10         59202
1     20         59202
2     30         59202
3     40         59202
4     50         21806

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\application_genres.csv
Columns: 2
['appid', 'genre_id']

   appid  genre_id
0     10       122
1     20       122
2     30       122
3     40       122
4     50       122

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\application_platforms.csv
Columns: 2
['appid', 'platform_id']

   appid  platform_id
0     10            1
1     10            2
2     10            3
3     20            1
4     20            2

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\application_publishers.csv
Columns: 2
['appid', 'publisher_id']

   appid  publisher_id
0     10         50182
1     20         50182
2     30         50182
3     40         50182
4     50         50182

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\categories.csv
Columns: 2
['id', 'name']

   id                   name
0   1   Remote Play en móvil
1   2          Flera spelare
2   3   Tablette Remote Play
3   4            Multiplayer
4   5  Таблицы лидеров Steam

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\developers.csv
Columns: 2
['id', 'name']

   id                  name
0   1   Skala Entertainment
1   2             Flicksync
2   3  SN Mobile Technology
3   4         Chestnut Team
4   5           SQYD.studio

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\genres.csv
Columns: 2
['id', 'name']

   id                        name
0   1                    Aventură
1   2  Многопользовательские игры
2   3                   Nezávislé
3   4                   Strategie
4   5                    Strategy

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\platforms.csv
Columns: 2
['id', 'name']

   id     name
0   1  windows
1   2      mac
2   3    linux

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\publishers.csv
Columns: 2
['id', 'name']

   id                   name
0   1    Skala Entertainment
1   2  Playdigious Originals
2   3   SN Mobile Technology
3   4            SQYD.studio
4   5         Susewind Games

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2025\steam_dataset_2025_csv\reviews.csv
Columns: 23
['recommendationid', 'appid', 'author_steamid', 'author_num_games_owned', 'author_num_reviews', 'author_playtime_forever', 'author_playtime_last_two_weeks', 'author_playtime_at_review', 'author_last_played', 'language', 'review_text', 'timestamp_created', 'timestamp_updated', 'voted_up', 'votes_up', 'votes_funny', 'weighted_vote_score', 'comment_count', 'steam_purchase', 'received_for_free', 'written_during_early_access', 'created_at', 'updated_at']

,recommendationid,appid,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,language,...,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,created_at,updated_at
0,10000000,264220,76561198085405844,760,74,12,0,12.0,1399059573,polish,...,True,0,1,0.459906,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
1,100001066,1006440,76561198014439859,485,234,424,0,424.0,1632666417,russian,...,True,8,0,0.630770,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
2,100002344,320721,76561198048038590,0,385,0,0,NaN,0,german,...,False,1,0,0.523810,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
3,100002361,1604700,76561197994386273,0,3,86,0,86.0,1632674318,english,...,True,3,0,0.541985,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
4,100002504,1338560,76561198138996331,816,26,25,0,25.0,1632639242,english,...,True,1,0,0.523810,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_2021_2025\a_steam_data_2021_2025.csv
Columns: 10
['appid', 'name', 'release_year', 'release_date', 'genres', 'categories', 'price', 'recommendations', 'developer', 'publisher']

,appid,name,release_year,release_date,genres,categories,price,recommendations,developer,publisher
0,3057270,Seafarer's Gambit,2024,"Jul 5, 2024",Action;Adventure;Indie;RPG;Strategy,Single-player;Family Sharing,3.99,0,Bouncy Rocket Studios,Bouncy Rocket Studios
1,3822840,Capitalist Misadventures,2025,"Jul 25, 2025",Casual;Indie;Simulation;Strategy,Single-player;Save Anytime;Family Sharing,7.99,0,Caramelo Studios,Caramelo Studios
2,3216640,The Beast and the Princess,2025,"Jun 17, 2025",Adventure;Indie;Strategy,Single-player;Steam Achievements;Full controll...,12.99,0,Libragames,Libragames
3,2403620,Air Twister,2023,"Nov 10, 2023",Action;Adventure;Indie,Single-player;Steam Achievements;Full controll...,24.99,0,YS Net,ININ
4,1538040,Horde Slayer,2021,"Mar 19, 2021",Action;Adventure;Casual;Indie;RPG;Early Access,Single-player;Steam Achievements;Full controll...,3.99,0,Wagner Rodrigues,Wagner Rodrigues

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\monthly_players\steamcharts.csv
Columns: 7
['month', 'avg_players', 'gain', 'gain_percent', 'peak_players', 'name', 'steam_appid']

,month,avg_players,gain,gain_percent,peak_players,name,steam_appid
0,Sep-25,7805.25,883.12,0.1276,13254,Counter-Strike,10
1,Aug-25,6922.13,-449.35,-0.0610,12168,Counter-Strike,10
2,Jul-25,7371.48,-833.50,-0.1016,13951,Counter-Strike,10
3,Jun-25,8204.98,-847.53,-0.0936,15798,Counter-Strike,10
4,May-25,9052.51,-471.31,-0.0495,15333,Counter-Strike,10

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\recommendations\games.csv
Columns: 13
['app_id', 'title', 'date_release', 'win', 'mac', 'linux', 'rating', 'positive_ratio', 'user_reviews', 'price_final', 'price_original', 'discount', 'steam_deck']

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\recommendations\recommendations.csv
Columns: 8
['app_id', 'helpful', 'funny', 'date', 'is_recommended', 'hours', 'user_id', 'review_id']

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
0,975370,0,0,2022-12-12,True,36.3,51580,0
1,304390,4,0,2017-02-17,False,11.5,2586,1
2,1085660,2,0,2019-11-17,True,336.5,253880,2
3,703080,0,0,2022-09-23,True,27.4,259432,3
4,526870,0,0,2021-01-10,True,7.9,23869,4

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\recommendations\users.csv
Columns: 3
['user_id', 'products', 'reviews']

    user_id  products  reviews
0   7360263       359        0
1  14020781       156        1
2   8762579       329        4
3   4820647       176        4
4   5167327        98        2

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_artemiloff\games_march2025_cleaned.csv
Columns: 47
['appid', 'name', 'release_date', 'required_age', 'price', 'dlc_count', 'detailed_description', 'about_the_game', 'short_description', 'reviews', 'header_image', 'website', 'support_url', 'support_email', 'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url', 'achievements', 'recommendations', 'notes', 'supported_languages', 'full_audio_languages', 'packages', 'developers', 'publishers', 'categories', 'genres', 'screenshots', 'movies', 'user_score', 'score_rank', 'positive', 'negative', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'discount', 'peak_ccu', 'tags', 'pct_pos_total', 'num_reviews_total', 'pct_pos_recent', 'num_reviews_recent']

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,3.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,682,2434,306,80,89916,"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, '...",84,1168020,76,12608

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_artemiloff\games_march2025_full.csv
Columns: 47
['appid', 'name', 'release_date', 'required_age', 'price', 'dlc_count', 'detailed_description', 'about_the_game', 'short_description', 'reviews', 'header_image', 'website', 'support_url', 'support_email', 'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url', 'achievements', 'recommendations', 'notes', 'supported_languages', 'full_audio_languages', 'packages', 'developers', 'publishers', 'categories', 'genres', 'screenshots', 'movies', 'user_score', 'score_rank', 'positive', 'negative', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'discount', 'peak_ccu', 'tags', 'pct_pos_total', 'num_reviews_total', 'pct_pos_recent', 'num_reviews_recent']

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,488824,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,19.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,0,0,0,0,0,"{'FPS': 8082, 'Multiplayer': 6139, 'Tactical':...",84,1168404,76,13017

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_artemiloff\games_may2024_cleaned.csv
Columns: 46
['AppID', 'name', 'release_date', 'required_age', 'price', 'dlc_count', 'detailed_description', 'about_the_game', 'short_description', 'reviews', 'header_image', 'website', 'support_url', 'support_email', 'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url', 'achievements', 'recommendations', 'notes', 'supported_languages', 'full_audio_languages', 'packages', 'developers', 'publishers', 'categories', 'genres', 'screenshots', 'movies', 'user_score', 'score_rank', 'positive', 'negative', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'peak_ccu', 'tags', 'pct_pos_total', 'num_reviews_total', 'pct_pos_recent', 'num_reviews_recent']

,AppID,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,29018,753,6078,352,1362469,"{'FPS': 90076, 'Shooter': 64786, 'Multiplayer'...",87,8071426,80,56072
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,590582,"{'Survival': 14611, 'Shooter': 12477, 'Battle ...",58,2365012,68,19517
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,35557,1327,1163,977,668192,"{'Free to Play': 59559, 'MOBA': 19966, 'Multip...",81,2247365,71,23832
3,271590,Grand Theft Auto V,2015-04-13,17,0.00,1,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,12898,590,6910,235,133571,"{'Open World': 31998, 'Action': 23177, 'Multip...",87,1643791,92,16181
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,19.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,16213,578,3016,331,68162,"{'FPS': 9689, 'PvP': 9073, 'e-sports': 9026, '...",85,1091695,77,10566

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\games_artemiloff\games_may2024_full.csv
Columns: 46
['AppID', 'name', 'release_date', 'required_age', 'price', 'dlc_count', 'detailed_description', 'about_the_game', 'short_description', 'reviews', 'header_image', 'website', 'support_url', 'support_email', 'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url', 'achievements', 'recommendations', 'notes', 'supported_languages', 'full_audio_languages', 'packages', 'developers', 'publishers', 'categories', 'genres', 'screenshots', 'movies', 'user_score', 'score_rank', 'positive', 'negative', 'estimated_owners', 'average_playtime_forever', 'average_playtime_2weeks', 'median_playtime_forever', 'median_playtime_2weeks', 'peak_ccu', 'tags', 'pct_pos_total', 'num_reviews_total', 'pct_pos_recent', 'num_reviews_recent']

,AppID,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,29018,753,6078,352,1362469,"{'FPS': 90076, 'Shooter': 64786, 'Multiplayer'...",87,8071426,80,56072
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,590582,"{'Survival': 14611, 'Shooter': 12477, 'Battle ...",58,2365012,68,19517
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,35557,1327,1163,977,668192,"{'Free to Play': 59559, 'MOBA': 19966, 'Multip...",81,2247365,71,23832
3,271590,Grand Theft Auto V,2015-04-13,17,0.00,1,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,12898,590,6910,235,133571,"{'Open World': 31998, 'Action': 23177, 'Multip...",87,1643791,92,16181
4,488822,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,19.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,0,0,0,0,0,"{'FPS': 8078, 'Multiplayer': 6138, 'Tactical':...",85,1092266,76,10481

====================================================================================================
C:\Users\245108\Desktop\gaming-data-analysis\raw\steam\reviews\dataset.csv
Columns: 5
['app_id', 'app_name', 'review_text', 'review_score', 'review_votes']

,app_id,app_name,review_text,review_score,review_votes
0,10,Counter-Strike,Ruined my life.,1,0
1,10,Counter-Strike,This will be more of a ''my experience with th...,1,1
2,10,Counter-Strike,This game saved my virginity.,1,0
3,10,Counter-Strike,• Do you like original games? • Do you like ga...,1,0
4,10,Counter-Strike,"Easy to learn, hard to master.",1,1

In [32]:
file_catalog_df.sort_values(
    "size_mb",
    ascending=False
).reset_index(drop=True)

,dataset,file,path,type,size_mb
0,rawg_games,videogames_data.jsonl,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON Lines,4101.47
1,steam_reviews,dataset.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,2060.77
2,steam_recommendations,recommendations.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1929.50
3,rawg_games,videogames_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1907.80
4,rawg_games,videogames_data.parquet,C:\Users\245108\Desktop\gaming-data-analysis\r...,Parquet,964.80
5,steam_games_fronkongames,games.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,925.28
6,steam_games_2025,reviews.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,638.78
7,steam_games_artemiloff,games_march2025_full.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,449.65
8,steam_games_artemiloff,games_march2025_cleaned.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,446.93
9,steam_games_artemiloff,games_may2024_full.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,405.23
10,steam_games_artemiloff,games_may2024_cleaned.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,402.75
11,steam_games_fronkongames,games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,382.56
12,steam_recommendations,users.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,184.12
13,steam_games_2025,applications.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,171.74
14,steam_monthly_players,steamcharts.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,36.13
15,ultimate_games,Ultimate_Games_Dataset.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,27.54
16,steam_recommendations,games_metadata.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,16.74
17,steam_games_2025,application_categories.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,11.84
18,steam_games_2021_2025,a_steam_data_2021_2025.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,11.11
19,steam_games_2025,application_genres.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,6.21
20,steam_recommendations,games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,4.64
21,metacritic_vs_steam,metacritic_Toppc_games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.60
22,metacritic_vs_steam,metacritic_Toppc_games_clean.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.53
23,steam_games_2025,application_developers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.27
24,steam_games_2025,application_platforms.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,3.11
25,steam_games_2025,application_publishers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,2.90
26,steam_games_2025,developers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.97
27,steam_games_2025,publishers.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.68
28,twitch_evolution,Twitch_game_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.56
29,metacritic_vs_steam,steam_spy_data_clean.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.23
30,metacritic_vs_steam,steam_spy_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1.15
31,epic_games,epic games store-video games.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.25
32,twitch_streamers,datasetV2.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.12
33,steam_games_2021_2025,collect_data_v2.py,C:\Users\245108\Desktop\gaming-data-analysis\r...,.PY,0.01
34,twitch_evolution,Twitch_global_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
35,steam_games_2025,categories.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
36,epic_games,epic_games_editor.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
37,epic_games,epic-games-demo.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.01
38,steam_games_2025,MANIFEST.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,0.00
39,epic_games,epic-games-apps.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00
40,steam_games_2025,platforms.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00
41,steam_games_2025,genres.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,0.00

потенциально большие

In [33]:
LARGE_FILE_THRESHOLD_MB = 500

large_files = file_catalog_df[
    file_catalog_df["size_mb"] >= LARGE_FILE_THRESHOLD_MB
].sort_values(
    "size_mb",
    ascending=False
)

large_files

,dataset,file,path,type,size_mb
9,rawg_games,videogames_data.jsonl,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON Lines,4101.47
41,steam_reviews,dataset.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,2060.77
35,steam_recommendations,recommendations.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1929.50
7,rawg_games,videogames_data.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,1907.80
8,rawg_games,videogames_data.parquet,C:\Users\245108\Desktop\gaming-data-analysis\r...,Parquet,964.80
2,steam_games_fronkongames,games.json,C:\Users\245108\Desktop\gaming-data-analysis\r...,JSON,925.28
29,steam_games_2025,reviews.csv,C:\Users\245108\Desktop\gaming-data-analysis\r...,CSV,638.78

In [34]:
print(file_catalog_df['size_mb'].sum()/1024)

14.755869140625002

In [35]:
metadata_dir = PROJECT_ROOT / "docs"
metadata_dir.mkdir(exist_ok=True)

file_catalog_df.to_csv(
    metadata_dir / "downloaded_files.csv",
    index=False
)

In [36]:
print("=" * 80)
print("DATA ACQUISITION SUMMARY")
print("=" * 80)

print(f"Kaggle datasets requested: {len(KAGGLE_DATASETS)}")
print(f"Successfully downloaded:    {len(downloaded_datasets)}")
print(f"Files copied to raw/:       {len(file_catalog_df)}")
print(f"Large files (>500 MB):      {len(large_files)}")

print("\nSources:")
for name in downloaded_datasets:
    print(f"- {name}")

================================================================================
DATA ACQUISITION SUMMARY
================================================================================
Kaggle datasets requested: 13
Successfully downloaded:    13
Files copied to raw/:       42
Large files (>500 MB):      7

Sources:
- twitch_streamers
- steam_games_fronkongames
- epic_games
- rawg_games
- ultimate_games
- twitch_evolution
- metacritic_vs_steam
- steam_games_2025
- steam_games_2021_2025
- steam_monthly_players
- steam_recommendations
- steam_games_artemiloff
- steam_reviews